### ISSUE TITLE
[Feature] Guide - Uploading Images & Videos

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/astro-cloudinary#17]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Create a new guide in the documentation that details Uploading Images & Videos

## **Describe the solution you'd like**

This guide should start off as a copy of the Next.js version: https://next.cloudinary.dev/guides/uploading-images-and-videos

The markdown/MDX can be found in the Next.js repo to make it easier to copy over: https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/guides/uploading-images-and-videos.mdx

Once the primary document is copied over:
- Update the components based on the Astro Cloudinary documentation usage (see other documentation pages)
- Update any usage patterns to reference Astro Cloudinary components
- Suggest any improvements to the guide to make it easier for people to understand and provide SEO value

This guide is lacking in depth, please be sure to include more content that can help people understand how to use the tools provided by the SDK.

**Comment by RaghavMangla** [comment]
Hi, I'd like to work on this issue

**Comment by colbyfayock** [comment]
we'll start with the other issue and can work on other issues 1 by 1 unless someone else takes it first. thanks

**Comment by RaghavMangla** [comment]
Hi, can I work on this issue

**Comment by RaghavMangla** [comment]
Hi! this is my PR: https://github.com/cloudinary-community/astro-cloudinary/pull/48, lmk if any changes are required

**Comment by RaghavMangla** [comment]
Hi! If everything looks fine, I think we can close this issue

**Comment by RaghavMangla** [comment]
Hi! My PR: #48, can u pls provide a review, let me know if any changes are needed

**Comment by RaghavMangla** [comment]
Hi! My PR: https://github.com/cloudinary-community/astro-cloudinary/pull/48, can u pls provide a review
