### ISSUE TITLE
[Feature] Guide - Background Removal

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/astro-cloudinary#18]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Create a new guide in the documentation that details Background Removal

## **Describe the solution you'd like**

This guide should start off as a copy of the Next.js version: https://next.cloudinary.dev/guides/background-removal

The markdown/MDX can be found in the Next.js repo to make it easier to copy over: https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/guides/background-removal.mdx
Once the primary document is copied over:
- Update the components based on the Astro Cloudinary documentation usage (see other documentation pages)
- Update any usage patterns to reference Astro Cloudinary components
- Suggest any improvements to the guide to make it easier for people to understand and provide SEO value

This guide is lacking in depth, please be sure to include more content that can help people understand how to use the tools provided by the SDK.

**Comment by RaghavMangla** [comment]
Hi, I'd like to work on this

**Comment by colbyfayock** [comment]
hi @RaghavMangla you can work on 1 issue at a time. would you like to work on this first?

**Comment by RaghavMangla** [comment]
yes sure, I'll work on 1 issue first, can i work on this issue,
https://github.com/cloudinary-community/astro-cloudinary/issues/21

**Comment by kcoderhtml** [comment]
I can write this!

**Comment by colbyfayock** [comment]
all yours!

**Comment by smv1256** [comment]
Hi, has this guide been written? If not, I can do it!
