### ISSUE TITLE
[Feature] Guide - Delivering Remote Images

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/astro-cloudinary#21]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Create a new guide in the documentation that details Delivering Remote Images

## **Describe the solution you'd like**

Delivering Remote Images should describe two ways to handle remote images including the images using the fetch API via:

```
deliveryType="fetch"
```

And using auto-upload via URL mapping, which would be handled using the UI and URL patterns

How: https://www.youtube.com/watch?v=LJhsn5A0PFE

**Comment by RaghavMangla** [comment]
hey, i wanted to add the video link in the remote images and videos documentation as well, how to add that

<CldVideoPlayer
  src="https://www.youtube.com/watch?v=LJhsn5A0PFE"
  width="1920"
  height="1080"
  deliveryType="fetch"
  colors={{
    accent: '#4a90e2',
    base: '#ffffff',
    text: '#333333'
  }}
  fontFace="Arial"
/>

this is giving a failed to fetch error, apart from that is there any pre written documentation with examples with deliveryType="fetch", for auto uploading images and videos part, I have completed the documentation using the youtube video

**Comment by colbyfayock** [comment]
hey @RaghavMangla great idea! however you can't pass a youtube video as a source there

i haven't implemented it yet, but in the Next.js equivalent docs, i created a video component to embed videos like that

https://github.com/cloudinary-community/next-cloudinary/tree/main/docs/components/Video

https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/cldimage/basic-usage.mdx?plain=1#L184-L186

perhaps you can do something similar?

**Comment by RaghavMangla** [comment]
can u pls share a documentation abt using deliveryType="fetch"

**Comment by RaghavMangla** [comment]
Hi, please let me know if any changes are required in the PR

**Comment by RaghavMangla** [comment]
Hi! can u pls review my PR, I have made the required changes

**Comment by RaghavMangla** [comment]
Hi! If everything looks fine, I think we can close this issue

**Comment by RaghavMangla** [comment]
Hi! My PR: #44, Can u pls provide a review, lmk if any changes are needed
